### ISSUE TITLE
broadcasttx should check the response#code

### ISSUE THREAD

**Issue by ItsFunny** [strangelove-ventures/lens#183]
https://github.com/strangelove-ventures/lens/blob/main/client/broadcast.go#L70-L83

Hi, I have a question about Why do you only check the ErrWrongSequence code ? 
Maybe You can just return if the code is not successful

**Comment by jtieri** [comment]
We just merged a PR that is less rigid [here](https://github.com/strangelove-ventures/lens/pull/181)

**Comment by ItsFunny** [comment]
> We just merged a PR that is less rigid [here](https://github.com/strangelove-ventures/lens/pull/181)

Yes, You should throw out the error and the result 
Close

**Comment by jtieri** [comment]
> > We just merged a PR that is less rigid [here](https://github.com/strangelove-ventures/lens/pull/181)
> 
> Yes, You should throw out the error and the result Close

Could you elaborate a bit on what you mean by this?

**Comment by ItsFunny** [comment]
> > > We just merged a PR that is less rigid [here](https://github.com/strangelove-ventures/lens/pull/181)
> > 
> > 
> > Yes, You should throw out the error and the result Close
> 
> Could you elaborate a bit on what you mean by this?

I mean the pr you merged is quite what I want ,

**Comment by ItsFunny** [comment]
Thanks For Your Reply ,I will close it

**Comment by jtieri** [comment]
Yeah the error logging in the relayer should be more verbose because the error code is not entirely meaningful unless you go digging for more context.

I'll get a change made where the error is consumed in the relayer so that the error messages there are more helpful!
https://github.com/cosmos/relayer/blob/6bf11fcc5ab842b3410a7efe7274ecced4da3a5c/relayer/provider/cosmos/tx.go#L181-L184
